### ISSUE TITLE
Feature code

### ISSUE THREAD

**Issue by szemkhel** [mychaelgo/aws-sso-auto-login#1]
Hi there - I know it's a small bit, but are you considering code contributions to this project? i have tried to push branch with a feature i developed for myself - but i have no permission. 
<img width="496" alt="Screenshot 2024-01-06 at 07 00 50" src="https://github.com/mychaelgo/aws-sso-auto-login/assets/8437578/0353fb08-13ff-40d1-9d4d-2efbf51ec511">
Basically i work on several accounts simultaneously, and so i have a SSO helper that opens for me dozen of SSO sessions, this brings up dozen of tabs (automatically parsed by your script) - but that leaves me with many open tabs. I have made small update to code that will close automatically tabs on successful authentication, and id like to share it with you.

**Comment by mychaelgo** [comment]
@szemkhel , can you fork this repo instead?

> this brings up dozen of tabs (automatically parsed by your script) - but that leaves me with many open tabs

I think for the open tab already fixed in this PR https://github.com/mychaelgo/aws-sso-auto-login/pull/3, let me know if this works for you
