### ISSUE TITLE
doesn't work with new ui

### ISSUE THREAD

**Issue by jahlbornG** [mychaelgo/aws-sso-auto-login#2]
aws has changed their page layout and this plugin no longer seems to work.

**Comment by dfroberg** [comment]
Made it work with new UI.
https://github.com/mychaelgo/aws-sso-auto-login/pull/3

**Comment by mychaelgo** [comment]
@jahlbornG already resolved in PR https://github.com/mychaelgo/aws-sso-auto-login/pull/3
thanks @dfroberg
